// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsp395PRpDULrxQIoo4DBSYCrqgQVArxw',
    appId: '1:727478954656:web:4900c27e22a4cc6c8f77c5',
    messagingSenderId: '727478954656',
    projectId: 'dutyspin',
    authDomain: 'dutyspin.firebaseapp.com',
    storageBucket: 'dutyspin.firebasestorage.app',
    measurementId: 'G-ZME44MJTBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUb0Oujikk_0jgPNhV5DhdNmbDIdas3zA',
    appId: '1:727478954656:android:0793ca74295b0c558f77c5',
    messagingSenderId: '727478954656',
    projectId: 'dutyspin',
    storageBucket: 'dutyspin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLVWO5oEXEkrZYjg6r83Qg2TF5fPkx8W8',
    appId: '1:727478954656:ios:162bf68e7ccebd218f77c5',
    messagingSenderId: '727478954656',
    projectId: 'dutyspin',
    storageBucket: 'dutyspin.firebasestorage.app',
    iosBundleId: 'com.example.choreflowFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLVWO5oEXEkrZYjg6r83Qg2TF5fPkx8W8',
    appId: '1:727478954656:ios:162bf68e7ccebd218f77c5',
    messagingSenderId: '727478954656',
    projectId: 'dutyspin',
    storageBucket: 'dutyspin.firebasestorage.app',
    iosBundleId: 'com.example.choreflowFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsp395PRpDULrxQIoo4DBSYCrqgQVArxw',
    appId: '1:727478954656:web:4ad36653b62ba9008f77c5',
    messagingSenderId: '727478954656',
    projectId: 'dutyspin',
    authDomain: 'dutyspin.firebaseapp.com',
    storageBucket: 'dutyspin.firebasestorage.app',
    measurementId: 'G-L2LYYM6J4G',
  );
}
